jap_name = {
    "魟": "扶桑",
    "鲼": "山城",
    "鳌": "伊勢",
    "螯": "日向",
    "姈": "金剛",
    "妸": "比叡",
    "妱": "榛名",
    "姏": "霧島",
    "凰": "赤城",
    "鸾": "加賀",
    "凤": "祥鳳",
    "鹞": "瑞鳳",
    "獒": "高雄",
    "犬": "愛宕",
    "犮": "摩耶",
    "猋": "鳥海",
    "豺": "天龍",
    "豹": "龍田",
    "狸": "北上",
    "獾": "大井",
    "貉": "五十鈴",
    "狐": "夕張",
    "桐": "吹雪",
    "杉": "白雪",
    "杨": "初雪",
    "梧": "深雪",
    "枫": "暁",
    "栀": "響",
    "梓": "雷",
    "柏": "電",
    "柚": "綾波",
    "柿": "敷波",
    "鲨": "長門",
    "鲞": "陸奥",
    "鹩": "大鳳",
    "枭": "龍驤",
    "狼": "古鷹",
    "狌": "加古",
    "犹": "青葉",
    "猅": "衣笠",
    "凊": "川内",
    "凉": "神通",
    "凁": "那珂",
    "椛": "秋月",
    "栎": "涼月",
    "萩": "陽炎",
    "蒲": "不知火",
    "蓉": "黒潮",
    "莲": "雪風",
    "鹬": "瑞鶴",
    "鹤": "翔鶴",
    "鸴": "飛龍",
    "鸷": "蒼龍",
    "末": "信濃",
    "鸱": "飛鷹",
    "鸢": "隼鷹",
    "鹏": "鳳翔",
    "猨": "最上",
    "狻": "三隈",
    "狺": "鈴谷",
    "猁": "熊野",
    "狔": "香取",
    "淀": "大淀",
    "松": "睦月",
    "汀": "白露",
    "浜": "時雨",
    "汐": "村雨",
    "氿": "夕立",
    "萍": "嵐",
    "芒": "島風",
    "棌": "峯風",
    "杙": "宵月",
    "鬣": "妙高",
    "鹰": "神鷹",
    "竺": "竹",
    "杺": "初月",
    "犾": "羽黒",
    "芷": "天津風",
    "燕": "早春",
    "狪": "木曾",
    "雾": "天雾"
}

eng_name = {
    "胡德": "Hood",
    "扶桑": "Fusō",
    "山城": "Yamashiro",
    "伊势": "Ise",
    "日向": "Hyūga",
    "俾斯麦": "Bismarck",
    "提尔比茨": "Tirpitz",
    "纳尔逊": "Nelson",
    "罗德尼": "Rodney",
    "威尔士亲王": "Prince of Wales",
    "内华达": "Nevada",
    "俄克拉荷马": "Oklahoma",
    "安德烈亚·多利亚": "Andrea Doria",
    "金刚": "Kongō",
    "比睿": "Hiei",
    "榛名": "Haruna",
    "雾岛": "Kirishima",
    "声望": "Renown",
    "反击": "Repulse",
    "阿拉斯加": "Alaska",
    "关岛": "Guam",
    "赤城": "Akagi",
    "加贺": "Kaga",
    "祥凤": "Shōhō",
    "瑞凤": "Zuihō",
    "百眼巨人": "Argus",
    "兰利": "Langley",
    "突击者": "Ranger",
    "列克星敦": "Lexington",
    "萨拉托加": "Saratoga",
    "大黄蜂": "Hornet",
    "高雄": "Takao",
    "爱宕": "Atago",
    "摩耶": "Maya",
    "鸟海": "Chōkai",
    "希佩尔海军上将": "Admiral Hipper",
    "布吕歇尔": "Blücher",
    "欧根亲王": "Prinz Eugen",
    "威奇塔": "Wichita",
    "昆西": "Quincy",
    "天龙": "Tenryū",
    "龙田": "Tatsuta",
    "北上": "Kitayama",
    "大井": "Ōi",
    "五十铃": "Isuzu",
    "夕张": "Yūbari",
    "柯尼斯堡": "Königsberg",
    "卡尔斯鲁厄": "Karlsruhe",
    "科隆": "Köln",
    "天狼星": "Sirius",
    "林仙": "Arethusa",
    "加拉蒂亚": "Galatea",
    "佩内洛珀": "Penelope",
    "曙光女神": "Aurora",
    "奥马哈": "Omaha",
    "亚特兰大": "Atlanta",
    "朱诺": "Juneau",
    "布鲁克林": "Brooklyn",
    "海伦娜": "Helena",
    "宁海": "Ning Hai",
    "平海": "Ping Hai",
    "罗伯茨": "Roberts",
    "阿贝克隆比": "Abercrombie",
    "吹雪": "Fubuki",
    "白雪": "Shirayuki",
    "初雪": "Hatsuyuki",
    "深雪 ": "Miyuki",
    "晓": "Akatsuki",
    "响": "Hibiki",
    "雷": "Ikazuchi",
    "电": "Inazuma",
    "绫波": "Ayanami",
    "敷波": "Shikinami",
    "Z1": "Z1",
    "Z16": "Z16",
    "Z21": "Z21",
    "Z22": "Z22",
    "Z24": "Z24",
    "Z28": "Z28",
    "Z31": "Z31",
    "紫石英": "Amethyst",
    "萤火虫": "Glowworm",
    "标枪": "Javelin",
    "天后": "Juno",
    "黑背豺": "Jackal",
    "哥萨克人": "Cossack",
    "爱斯基摩人": "Eskimo",
    "旁遮普人": "Punjabi",
    "弗莱彻": "Fletcher",
    "卡辛杨": "Cassin Young",
    "安东尼": "Anthony",
    "布雷恩": "Braine",
    "基林": "Gearing",
    "基阿特": "Gyatt",
    "弗兰克·诺克斯": "Frank Knox",
    "鲍尔": "Power",
    "果敢": "Reshitelny",
    "沃克兰": "Vauquelin",
    "空想": "Le Fantasque",
    "狮": "Lion",
    "长门": "Nagato",
    "陆奥": "Mutsu",
    "皇家橡树": "Royal Oak",
    "厌战": "Warspite",
    "前卫": "Vanguard",
    "田纳西": "Tennessee",
    "加利福尼亚": "California",
    "科罗拉多": "Colorado",
    "马里兰": "Maryland",
    "西弗吉尼亚": "West Virginia",
    "华盛顿": "Washington",
    "维内托": "Vittorio Veneto",
    "黎塞留": "Richelieu",
    "沙恩霍斯特": "Scharnhorst",
    "格奈森瑙": "Gneisenau",
    "大凤": "Taihō",
    "齐柏林伯爵": "Graf Zeppelin",
    "皇家方舟": "Ark Royal",
    "约克城": "Yorktown",
    "企业": "Enterprise",
    "龙骧": "Ryūjō",
    "博格": "Bogue",
    "追赶者": "Chaser",
    "巨像": "Colossus",
    "普林斯顿": "Princeton",
    "独角兽": "Unicorn",
    "德意志": "Deutschland",
    "舍尔海军上将": "Admiral Scheer",
    "斯佩伯爵海军上将": "Admiral Graf Spee",
    "古鹰": "Furutaka",
    "加古": "Kako",
    "青叶": "Aoba",
    "衣笠": "Kinugasa",
    "伦敦": "London",
    "肯特": "Kent",
    "波特兰": "Portland",
    "印第安纳波利斯": "Indianapolis",
    "彭萨科拉": "Pensacola",
    "盐湖城": "Salt Lake City",
    "北安普顿": "Northampton",
    "休斯顿": "Houston",
    "新奥尔良": "New Orleans",
    "基洛夫": "Kirov",
    "川内": "Sendai",
    "神通": "Jintsū",
    "那珂": "Naka",
    "M计划": "M",
    "埃姆登": "Emden",
    "翡翠": "Emerald",
    "进取": "Enterprise",
    "爱丁堡": "Edinburgh",
    "贝尔法斯特": "Belfast",
    "勇敢": "Courageous",
    "光荣": "Glorious",
    "暴怒": "Furious",
    "圣地亚哥": "San Diego",
    "圣胡安": "San Juan",
    "摩尔曼斯克": "Murmansk",
    "德·鲁伊特": "De Ruyter",
    "逸仙": "Yat Sen",
    "维那莫依嫩": "Väinämöinen",
    "秋月": "Akizuki",
    "凉月": "Suzutsuki",
    "阳炎": "Kagerō",
    "不知火": "Shiranui",
    "黑潮": "Kuroshio",
    "雪风": "Yukikaze",
    "Z3": "Z3",
    "Z46": "Z46",
    "热心": "Ardent",
    "阿卡司塔": "Acasta",
    "索玛雷兹": "Saumarez",
    "维纳斯": "Venus",
    "军团": "Legion",
    "撒切尔": "Thatcher",
    "沙利文": "The Sullivans",
    "西格斯比": "Sigsbee",
    "奥班农": "O'Bannon",
    "威廉·D·波特": "William D. Porter",
    "波特": "Porter",
    "拉菲": "Laffey",
    "拉菲": "Laffey",
    "卡米契亚·内拉": "Camicia Nera",
    "阿维埃尔": "Aviere",
    "安东尼奥·达诺利": "Antonio Da Noli",
    "乌戈里尼·维瓦尔迪": "Ugolino Vivaldi",
    "塔什干": "Tashkent",
    "恩格斯": "Engels",
    "大青花鱼": "Albacore",
    "射水鱼": "Archerfish",
    "M1": "M1",
    "U47": "U47",
    "U505": "U505",
    "絮库夫": "Surcouf",
    "兴登堡": "Hindenburg",
    "伊丽莎白女王": "Queen Elizabeth",
    "约克公爵": "Duke of York",
    "北卡罗来纳": "North Carolina",
    "南达科他": "South Dakota",
    "马萨诸塞": "Massachusetts",
    "密苏里": "Missouri",
    "衣阿华": "Iowa",
    "卡约•杜伊里奥": "Caio Duilio",
    "罗马": "Roma",
    "苏联": "Sovetsky Soyuz",
    "敦刻尔克": "Dunkerque",
    "斯特拉斯堡": "Strasbourg",
    "古斯塔夫五世": "Gustav V",
    "瑞鹤": "Zuikaku",
    "翔鹤": "Shōkaku",
    "飞龙": "Hiryū",
    "苍龙": "Sōryū",
    "信浓": "Shinano",
    "可畏": "Formidable",
    "黄蜂": "Wasp",
    "埃塞克斯": "Essex",
    "飞鹰": "Hiyō",
    "隼鹰": "Junyō",
    "凤翔": "Hōshō",
    "竞技神": "Hermes",
    "贝亚恩": "Béarn",
    "最上": "Mogami",
    "三隈": "Mikuma",
    "铃谷": "Suzuya",
    "熊野": "Kumano",
    "萨福克": "Suffolk",
    "约克": "York",
    "埃克赛特": "Exeter",
    "旧金山": "San Francisco",
    "巴尔的摩": "Baltimore",
    "德梅因": "Des Moines",
    "扎拉": "Zara",
    "阿尔及利亚": "Algeria",
    "香取": "Katori",
    "大淀": "Ōyodo",
    "莱比锡": "Leipzig",
    "伍斯特": "Worcester",
    "奥克兰": "Oakland",
    "克利夫兰": "Cleveland",
    "应瑞": "Ying Swei",
    "肇和": "Chao Ho",
    "吞武里": "Thonburi",
    "睦月": "Mutsuki",
    "白露": "Shiratsuyu",
    "时雨": "Shigure",
    "村雨": "Murasame",
    "夕立": "Yūdachi",
    "岚": "Arashi",
    "岛风": "Shimakaze",
    "峰风": "Minekaze",
    "Z17": "Z17",
    "Z18": "Z18",
    "吸血鬼": "Vampire",
    "海达人": "Haida",
    "康弗斯": "Converse",
    "戴森": "Dyson",
    "克拉克斯顿": "Claxton",
    "霍埃尔": "Hoel",
    "塞缪尔•罗伯茨": "Samuel B. Roberts",
    "约翰斯顿": "Johnston",
    "雷鸣": "Gremyashchiy",
    "U81": "U81",
    "U96": "U96",
    "U156": "U156",
    "U1206": "U1206",
    "刺尾鱼": "Tang",
    "乔治·埃夫洛夫": "Georgios Averof",
    "苏赫巴托尔": "Sükhbaatar",
    "马汉": "Mahan",
    "圣路易斯": "St. Louis",
    "奥丁": "Óðinn",
    "圣女贞德": "Jeanne D'Arc",
    "英王乔治五世": "King George V",
    "巴夫勒尔": "Barfleur",
    "女灶神": "Vestal",
    "哥特兰": "Gotland",
    "诺夫哥罗德": "Novgorod",
    "库欣": "Cushing",
    "瓜达卡纳尔": "Guadalcanal",
    "纽伦堡": "Nürnberg",
    "阿贾克斯": "Ajax",
    "哥特雄狮": "Göta Lejon",
    "宵月": "Yoizuki",
    "明斯克": "Minsk",
    "M2": "M2",
    "毛奇": "Moltke",
    "不挠": "Indomitable",
    "鹞鹰": "Sparviero",
    "希尔曼": "Heermann",
    "基辅": "Kiev",
    "塔斯卡卢萨": "Tuscaloosa",
    "列克星敦": "Lexington",
    "诺福克": "Norfolk",
    "斯特雷特": "Sterett",
    "妙高": "Myōkō",
    "奥古斯塔": "Augusta",
    "卫士": "Defender",
    "无比": "Incomparable",
    "神鹰": "Shinyō",
    "德格拉斯": "De Grasse",
    "不惧": "Neustrashimy",
    "伏尔塔": "Volta",
    "竹": "Take",
    "伟大的庞贝": "Pompeo Magno",
    "天鹰": "Aquila",
    "帝国": "Impero",
    "波尔扎诺": "Bolzano",
    "龙骑兵": "Dragon",
    "江原": "Kang Won",
    "威斯康星": "Wisconsin",
    "谢菲尔德": "Sheffield",
    "蒙彼利埃": "Montpelier",
    "丹佛": "Denver",
    "初月": "Hatsuzuki",
    "菲尔普斯": "Phelps",
    "U-1405": "U-1405",
    "莫斯科": "Moscow",
    "斯维尔德洛夫": "Sverdlov",
    "阿尔贝托·迪·朱桑诺": "Alberto Di Giussano",
    "联合力量": "Viribus Unitis",
    "爱丽": "Elli",
    "羽黑": "Haguro",
    "天津风": "Amatsukaze",
    "吕-34": "Ro-34",
    "虎": "Tiger",
    "K1": "K1",
    "星座": "Constellation",
    "炽热": "Zhguchiy",
    "加纳里亚斯": "Canarias",
    "门德斯·努涅斯": "Mendez Nunez",
    "鹦鹉螺": "Nautilus",
    "乌尔里希·冯·胡滕": "Ulrich von Hutten",
    "塞德利茨": "Seydlitz",
    "克莱夫勋爵": "Lord Clive",
    "光辉": "Illustrious",
    "海王星": "Neptune",
    "早春": "Hayaharu",
    "达·芬奇": "Leonardo da Vinci",
    "汉考克": "Hancock",
    "圣哈辛托": "San Jacinto",
    "埃德加·居内": "Edgar Quinet",
    "木曾": "Kiso",
    "斯普利特": "Split",
    "圣乔治": "St George",
    "印第安纳": "Indiana",
    "坎伯兰": "Cumberland",
    "奥斯塔公爵": "Duca d'Aost",
    "法迪布鲁诺": "Faà di Bruno",
    "S113": "S113",
    "莉安夕": "U-2365",
    "海圻": "Hai Chi",
    "纽波特纽斯": "Newport News",
    "留里克": "Rurik",
    "库图佐夫": "Kutuzov",
    "查尔斯·亚当斯": "Charles Adams",
    "天雾": "Amagiri",
    "查尔斯·奥斯本": "Charles Ausburne",
    "泰勒": "Taylor",
    "闪电": "Blyskawica",
    "新墨西哥": "New Mexico",
    "斯大林格勒": "Stalingrad",
    "德里": "Delhi",
    "阿布鲁奇公爵": "Luigi di Savoia Duca Degli Abruzzi",
    "七省联盟": "De Zeven Provinciën",
    "胆大": "Mischievous",
    "U-35": "U-35",
    "格拉摩根": "Glamorgan",
    "怨仇": "Implacable",
    "乔治莱格": "Georges Leygues",
    "哈曼": "Hammann",
    "吕特晏斯": "Lütjens",
    "鲃鱼": "Barb",
    "新泽西": "New Jersey",
    "萨勒姆": "Salem",
    "黛朵": "Dido",
    "堪培拉": "Canberra",
    "加里波第": "Garibaldi",
    "凯利": "Kelly",
    "英格兰": "England",
    "47工程": "Project 47",
    "可怖": "Le Terrible",
    "阿金库尔": "Agincourt",
    "桑提": "Santee",
    "亚尔古水手": "Argonaut",
    "萨凡纳": "Savannah",
    "凤凰城": "Phoenix",
    "燕八哥": "Starling",
    "蒂默曼": "Timmerman",
    "史密斯": "Smith",
    "提尔比茨": "Tirpitz",
    "萝德尼": "Lodney",
    "内华达": "Nevada",
    "欧根亲王": "Prinz Eugen",
    "华盛顿": "Washington",
    "戈本": "Goeben",
    "塞班": "Saipan",
    "哥伦比亚": "Columbia",
    "马伊·布雷泽": "Maille Breze",
    "忠武": "Chung Mu"
}


def get_name(name):
    try:
        if name in jap_name:
            res = jap_name[name]
        else:
            res = eng_name[name]
        return res
    except KeyError:
        return name

# End of File
