from .api import WGR_API
from .boat import API_BOAT
from .campaign import API_CAMPAIGN
from .dock import API_DOCK
from .explore import API_EXPLORE
from .friend import API_FRIEND
from .pve import API_PVE
from .pvp import API_PVP
from .six import API_SIX
from .task import API_TASK
