
"""
DO **NOT** EDIT THIS FILE!

THIS FILE IS AUTO-GENERATED BY src/utils/__auto_gen__.py

Note that '_' leading functions are not imported!

If error comes from __init__.py, due largely to asynchronous update,
delete the __init__.py and re-run __auto_gen__.py
"""
    
from .general import (
    clear_desc, 
    force_quit, 
    get_app_version, get_color_option, get_color_scheme, get_curr_time, get_game_version, get_today, get_unixtime, 
    increase_sleep_interval, 
    reset_sleep_event, 
    set_sleep, stop_sleep_event, 
    ts_to_countdown, ts_to_date
)
from .shipname import (
    get_name
)
from .wgv_pyqt import (
    get_screen_center, get_user_resolution, 
    open_disclaimer, open_url, 
    popup_msg, 
    quit_application
)
