
"""
DO **NOT** EDIT THIS FILE!

THIS FILE IS AUTO-GENERATED BY src/utils/__auto_gen__.py

Note that '_' leading functions are not imported!

If error comes from __init__.py, due largely to asynchronous update,
delete the __init__.py and re-run __auto_gen__.py
"""
    
from .game_combat import (
    get_repair_type, 
    process_spy_json
)
from .game_info import (
    get_all_ship_types, get_build_type, get_combat_formation, get_ship_los, get_ship_type, get_war_evaluation
)
from .general import (
    clear_desc, 
    force_quit, 
    get_app_version, get_curr_time, get_game_version, 
    ts_to_countdown, ts_to_date
)
from .wgv_pyqt import (
    get_user_resolution, 
    open_disclaimer, open_url, 
    popup_msg, 
    quit_application
)
