name: 'Check commit message style'
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  push:
    branches:
      - master
      - menu-bar
      - side-dock
      - e6-auto
      - 'dev/*'

jobs:
  check-commit-message-style:
    name: Check commit message style
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: mristin/opinionated-commit-message@v2.2.0
        with:
          allow-one-liners: 'true'
          path-to-additional-verbs: '.github/workflows/additional-verbs.txt'